name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Login to Hub
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        
        - name: Run make build
          env: 
            DOCKERHUB_USERNAME: ${{ secrets. DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets. DOCKERHUB_TOKEN }}
          run: make build

        - name: Run make push
          env: 
              DOCKERHUB_USERNAME: ${{ secrets. DOCKERHUB_USERNAME }}
              DOCKERHUB_TOKEN: ${{ secrets. DOCKERHUB_TOKEN }}
          run: make push
